# Generated by Django 4.2.26 on 2025-11-05 14:29

from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserStats',
            fields=[
                ('user_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('total_storage_used', models.IntegerField(default=0)),
                ('original_storage_used', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(blank=True, null=True, upload_to=files.models.file_upload_path)),
                ('original_filename', models.CharField(db_index=True, max_length=255)),
                ('file_type', models.CharField(db_index=True, max_length=100)),
                ('size', models.IntegerField(db_index=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user_id', models.CharField(db_index=True, max_length=255)),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('is_reference', models.BooleanField(db_index=True, default=False)),
                ('original_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='references', related_query_name='reference', to='files.file')),
            ],
            options={
                'indexes': [models.Index(fields=['user_id'], name='idx_user_id'), models.Index(fields=['original_filename'], name='idx_original_filename'), models.Index(fields=['file_hash'], name='idx_file_hash'), models.Index(fields=['user_id', 'uploaded_at'], name='idx_user_uploaded'), models.Index(fields=['user_id', 'file_type'], name='idx_user_file_type'), models.Index(fields=['user_id', 'size'], name='idx_user_size'), models.Index(fields=['user_id', 'original_filename'], name='idx_user_filename_search'), models.Index(fields=['user_id', 'is_reference'], name='idx_user_is_reference'), models.Index(fields=['user_id', 'file_type', 'uploaded_at'], name='idx_user_type_date'), models.Index(fields=['user_id', 'size', 'uploaded_at'], name='idx_user_size_date'), models.Index(fields=['file_hash', 'is_reference'], name='idx_hash_is_reference')],
            },
        ),
    ]
